/*
 * data.js — Single source of truth for the portfolio content.
 * All texts, titles, media and dimensions are transcribed verbatim from
 * "Andrea Bolognino — Portfolio" (AB_PORTFOLIO_26t_1.pdf).
 * Edit this file to update the website; index.html / script.js render from it.
 */

const SITE = {
  name: "Andrea Bolognino",
  role: "Portfolio",
  domain: "www.andreabolognino.com",
  // No email/contact was provided in the portfolio. Add yours here when ready.
  email: "",
  statement:
    "My artistic research investigates processes of memory and imagination as " +
    "material forces that sediment, transform, and reorganize matter over time. " +
    "I explore forms of representation through different states of matter, treating " +
    "materials as active agents that retain traces of environmental, symbolic, and " +
    "cultural stratifications. These layered conditions reveal fragile ecological " +
    "equilibriums and challenge conventional understandings of landscape as a stable " +
    "or purely visual entity.\n\n" +
    "Rooted in painting and drawing, my practice expands into sculptural, installative, " +
    "and video-based forms, where images become spatial and matter behaves as a dynamic " +
    "process. I am particularly interested in moments of collapse, transformation, and " +
    "instability, where form remains provisional and open to change. My works function " +
    "as open systems, hosting fragments of symbolism and scientific observation, and " +
    "acting as witnesses to irreversible events, sudden ruptures, and the merging of " +
    "anatomical and geomorphic phenomena.\n\n" +
    "Through these processes, I seek to blur distinctions between body and landscape, " +
    "organic and inorganic, perception and materiality.",
};

// Helper for image paths
const img = (f) => `assets/images/${f}`;

/*
 * Each project: { id, title, year, venue, curator, summary, credits, works[] }
 * Each work: { src, title, medium, caption }  (caption used when no title)
 * Projects are listed newest-to-oldest, matching the portfolio order.
 */
const PROJECTS = [
  {
    id: "pictorial-hyperobjects",
    title: "Pictorial Hyperobjects",
    year: "ongoing",
    venue: "PhD Project in Visual Art and Creative Practices — Academy of Fine Arts Naples",
    subtitle: "for a contemporary expansion of landscape painting",
    summary:
      "Looking at the contemporary landscape as the coexistence of hyperobjects (Morton 2018), " +
      "phenomena of such vast spatio-temporal dimensions that they destabilize the dialectic " +
      "between subject and object, the project seeks to produce a corpus of “pictorial " +
      "hyperobjects” in order to interrogate and expand the pictorial medium through " +
      "hybridization with sculpture and with digital images generated by GANs, CNNs, and RNNs.\n\n" +
      "The aim is to conduct a multidimensional inquiry into landscape through both material and " +
      "digital experiments, with a particular focus on the cartographic tool of the map. Starting " +
      "from the conception of the “object” as active matter (Friedmann-Krauthausen 2021), " +
      "it addresses crucial questions of the present: How does art respond to the life of objects? " +
      "Can painting subvert the perception of landscape as an object to be possessed, fostering " +
      "instead an eco-critical awareness? Is it possible to create a work that is viscous and " +
      "unlimited (Morton 2018) like the hyperobjects within which it is conceived?\n\n" +
      "Early experiments have focused on decomposition, using organic residues and mold to generate " +
      "surfaces marked by living traces. The erosion and disintegration of paper by microorganisms " +
      "and insects produced compositions reminiscent of aerial views of landscapes. While mold is " +
      "usually associated with decay and death, the project reinterprets it as a sign of " +
      "regeneration, situating these surfaces at the intersection of ecological and political reflection.",
    works: [
      { src: img("p04_1.jpg"), title: "Initial practice-based research findings", medium: "Microorganisms, charcoal and oil on paper and plastic, dimensions variable" },
      { src: img("p04_2.jpg"), title: "Initial practice-based research findings", medium: "Microorganisms, charcoal and oil on paper and plastic, dimensions variable" },
      { src: img("p04_3.jpg"), title: "Initial practice-based research findings", medium: "Microorganisms, charcoal and oil on paper and plastic, dimensions variable" },
      { src: img("p05_1.jpg"), title: "Initial practice-based research findings", medium: "Microorganisms, charcoal and oil on paper and plastic, dimensions variable" },
      { src: img("p05_2.jpg"), title: "Initial practice-based research findings", medium: "Microorganisms, charcoal and oil on paper and plastic, dimensions variable" },
      { src: img("p05_3.jpg"), title: "Initial practice-based research findings", medium: "Microorganisms, charcoal and oil on paper and plastic, dimensions variable" },
      { src: img("p06_1.jpg"), title: "Initial practice-based research findings", medium: "Microorganisms, charcoal and oil on paper and plastic, dimensions variable" },
      { src: img("p06_2.jpg"), title: "Initial practice-based research findings", medium: "Microorganisms, charcoal and oil on paper and plastic, dimensions variable" },
      { src: img("p06_3.jpg"), title: "Initial practice-based research findings", medium: "Microorganisms, charcoal and oil on paper and plastic, dimensions variable" },
      { src: img("p07_1.jpg"), title: "Extension of the practice into Video Art", medium: "Still from video — triadic apparatus: macro lens on a smartphone camera, an endoscope, and a webcam + Vjing softwares" },
      { src: img("p07_2.jpg"), title: "Extension of the practice into Video Art", medium: "Still from video" },
      { src: img("p07_3.jpg"), title: "Extension of the practice into Video Art", medium: "Still from video" },
      { src: img("p07_4.jpg"), title: "Extension of the practice into Video Art", medium: "Still from video" },
      { src: img("p07_5.jpg"), title: "Extension of the practice into Video Art", medium: "Still from video" },
      { src: img("p07_6.jpg"), title: "Extension of the practice into Video Art", medium: "Still from video" },
      { src: img("p07_7.jpg"), title: "Extension of the practice into Video Art", medium: "Still from video" },
      { src: img("p07_8.jpg"), title: "Extension of the practice into Video Art", medium: "Still from video" },
      { src: img("p07_9.jpg"), title: "Extension of the practice into Video Art", medium: "Still from video" },
      { src: img("p07_10.jpg"), title: "Extension of the practice into Video Art", medium: "Still from video" },
      { src: img("p07_11.jpg"), title: "Extension of the practice into Video Art", medium: "Still from video" },
      { src: img("p07_12.jpg"), title: "Extension of the practice into Video Art", medium: "Still from video" },
    ],
  },
  {
    id: "osservatorio",
    title: "Osservatorio",
    year: "2024",
    venue: "Galleria Acappella",
    credits: "Photo credits: Danilo Donzelli",
    summary:
      "It’s unsettling the constant branching out of the tentative gaze that observes a drawing " +
      "or a canvas by Andrea Bolognino. A feeling of losing oneself in a labyrinth, only to find a " +
      "possible way out in a detail, a mark, a specific shade. In Bolognino’s work, observation " +
      "manifests itself as a process of exploration of the multiple layers and dimensions that make " +
      "up the fabric of life. His canvases and papers are veritable visual palimpsests, where images " +
      "overlap and undermine one another, creating a tangle of lines and forms that are as suggestive " +
      "as they are enigmatic.\n\n" +
      "Thus, the artist moves away from the traditional idea of mimetic representation to a more " +
      "complex and diverse view of reality. Bolognino does not use painting as a space for " +
      "representation. He uses it as a plastic dimension in which the viewer and the matter develop " +
      "a relationship capable of generating bewilderment.\n\n— Lucrezia Longobardi",
    works: [
      { src: img("p09_1.jpg"), title: "Osservatorio", medium: "Installation view, Galleria Acappella" },
      { src: img("p10_1.jpg"), title: "Anelli di crescita", medium: "Charcoal, graphite, pastels and oil on paper on wood — 95 × 150 cm" },
      { src: img("p10_2.jpg"), title: "Sezione sottile di granito", medium: "Charcoal, graphite, pastels and oil on paper on wood — 95 × 150 cm" },
      { src: img("p11_1.jpg"), title: "La città è una macchina inutile", medium: "Plaster, acrylic, oil, collage, ink transfer, pastels on canvas — 184 × 149 cm" },
      { src: img("p12_1.jpg"), title: "Osservatorio", medium: "Installation view, Galleria Acappella" },
      { src: img("p13_1.jpg"), title: "Schwarzwald", medium: "Charcoal, graphite, pastels and oil on paper — 18 × 25 cm" },
      { src: img("p13_2.jpg"), title: "Cristalli di rame nativo", medium: "Charcoal, oil and pastels on paper — 10 × 15 cm" },
      { src: img("p14_1.jpg"), title: "Osservatorio", medium: "Installation view, Galleria Acappella" },
    ],
  },
  {
    id: "il-guscio",
    title: "Il Guscio",
    year: "2022",
    venue: "Officine San Carlo",
    curator: "Curated by Lucrezia Longobardi and Nora De Blasio",
    summary:
      "“Giving life to a space in disintegration, Bolognino’s work inhabits the disillusionment " +
      "of dreams abandoned while growing up, of all the hopes and desires that animated the primary age " +
      "and that, inevitably, have been let go to the oblivion of a present that does not allow distractions. " +
      "The quagmire is, therefore, the natural element in which to find all that we have had to part with, " +
      "along with the viscosity of time dissolved behind us.”\n\n— Lucrezia Longobardi",
    works: [
      { src: img("p16_1.jpg"), title: "Il Guscio", medium: "Glass case, soil, plants, found objects, plaster, clay, glue, paper — 250 × 300 × 300 cm" },
      { src: img("p17_1.jpg"), title: "Il Guscio", medium: "Glass case, soil, plants, found objects, plaster, clay, glue, paper — detail" },
      { src: img("p17_2.jpg"), title: "Il Guscio", medium: "Glass case, soil, plants, found objects, plaster, clay, glue, paper — detail" },
    ],
  },
  {
    id: "automa-autore",
    title: "Automa-Autore",
    year: "2022",
    venue: "Galleria UnosuNove",
    curator: "Curated by Simone Zacchini",
    summary:
      "The work stems from the etymon of the word encyclopedia, from the Greek enkýklios paideîa, " +
      "“circular instruction,” to investigate a space of contact between art and science in which " +
      "to allow a futuristic being-in-the-world to germinate. Thus, a condition is generated in which real " +
      "and virtual overlap fluidly thanks to a yet unseen quality of technology, which amplifies the human, " +
      "merging within it. In conceiving the work, I was inspired by the impossible task of the protagonist " +
      "of La Macchina Mondiale (Paolo Volponi, 1965).",
    credits: "Installation view, Figure Out, UnoSuNove Gallery, Rome — Photo credits: Giorgio Benni",
    works: [
      { src: img("p19_1.jpg"), title: "Automa-Autore", medium: "Installation view, Figure Out, UnoSuNove Gallery, Rome" },
      { src: img("p20_1.jpg"), title: "Automa-Autore", medium: "Charcoal and pigments on paper mounted on canvas — 150 × 230 cm" },
      { src: img("p21_1.jpg"), title: "Untitled, from the series Automa-Autore", medium: "Watercolour and graphite on paper — 30 × 22 cm" },
      { src: img("p21_2.jpg"), title: "Untitled, from the series Automa-Autore", medium: "Watercolour and charcoal on paper — 25 × 30 cm" },
    ],
  },
  {
    id: "metamorphica",
    title: "Metamorphica",
    year: "2022 / ongoing",
    venue: "Series of mixed media drawings and paintings on different surfaces",
    summary:
      "Metamorphica is an imaginative journey from the microscopic to the macroscopic and vice versa. " +
      "On my work table, I arranged objets trouvés accumulated over time. I spent my time observing " +
      "and meditating on them and thus, with my eyes closed, I landed on pluriform landscapes of memory " +
      "and imagination. Sometimes it is the texture or material of the objects that triggers an " +
      "imaginative reaction, sometimes their composition, and sometimes the variations of light that hit " +
      "them. Each element is linked to the other in a constant stream of metamorphosis, from material to " +
      "material, from leaf to fabric, from fork to sea urchin.",
    works: [
      { src: img("p23_1.jpg"), title: "Untitled (metamorphica)", medium: "Graphite, pastels, oil and watercolour on paper — 45 × 30 cm" },
      { src: img("p23_2.jpg"), title: "Untitled (metamorphica)", medium: "Graphite, pastels, oil and watercolour on paper — 55 × 37 cm" },
      { src: img("p24_1.jpg"), title: "Untitled (metamorphica)", medium: "Charcoal, glue, pigments, oil and acrylic on paper in wood frame — 35 × 30 cm" },
      { src: img("p25_1.jpg"), title: "Il deserto dei Tartari", medium: "Charcoal, graphite, pastels and oil on paper in wood frame — 15 × 20 cm (×3)" },
    ],
  },
  {
    id: "i-giganti",
    title: "I Giganti",
    year: "2022",
    venue: "Galleria Acappella",
    credits: "Photo credits: Danilo Donzelli",
    summary:
      "The research project “I Giganti” came about as an attempt to translate the collection " +
      "nachts leuchten die schiffe, by the German poet Nico Bleutge, into my visual language. I retraced " +
      "the poet’s path, finding myself in the first person on the trail of Alfred Döblin and, in " +
      "particular, his science fiction novel Giganten (1932). The figure of Giants as beings formed from " +
      "organic and inorganic material in constant metamorphosis thus also stimulated my imagination, " +
      "causing me to delve in another light into a pivotal point of my poetics: the dialogue between the " +
      "human body and the machine.",
    works: [
      { src: img("p27_1.jpg"), title: "I Giganti", medium: "Installation view, Galleria Acappella" },
      { src: img("p28_1.jpg"), title: "Kylin", medium: "Graphite, oil and charcoal on paper — 100 × 70 cm" },
      { src: img("p28_2.jpg"), title: "Wieschinska", medium: "Graphite, oil and pastel on paper — 29 × 41 cm" },
      { src: img("p29_1.jpg"), title: "Veli di tormalina", medium: "Oil on paper — 21 × 29 cm" },
      { src: img("p30_1.jpg"), title: "Scrolling", medium: "Graphite, pastels, oil and collage on paper — 29 × 41 cm" },
      { src: img("p30_2.jpg"), title: "Senza Titolo (studio da Chaim Soutine)", medium: "Graphite, oil and pastel on paper — 50 × 30 cm" },
      { src: img("p31_1.jpg"), title: "I Giganti", medium: "Installation view, Galleria Acappella" },
    ],
  },
  {
    id: "corpo-aumentato",
    title: "Corpo aumentato",
    year: "2022",
    venue: "Series of mixed media paintings on polyester",
    summary:
      "The augmented body establishes a dialogue with the votive shrine as a characteristic architectural " +
      "element of the city of Naples. With this work, I started from the configuration of the body of the " +
      "Saints, as a place where the presence of the divine is visible, often through mutilation and wounds, " +
      "to reflect on the status of the contemporary body, augmented, hybridized, grafted by elements of an " +
      "artificial and technological nature. Thus, at the center of the installation is the idea of a new " +
      "contaminated anatomy, where imagination redesigns the human figure as a battleground between biology " +
      "and technological innovation.",
    works: [
      { src: img("p33_1.jpg"), title: "Untitled (corpo aumentato)", medium: "Oil, pigments and charcoal on polyester — 21 × 29 cm — installation view" },
      { src: img("p34_1.jpg"), title: "Untitled (corpo aumentato)", medium: "Charcoal and acrylic on polyester — 21 × 29 cm" },
    ],
  },
  {
    id: "cecita-accecamento-oltraggio",
    title: "Cecità accecamento oltraggio",
    year: "2022",
    venue: "Museo e Real Bosco di Capodimonte",
    curator: "Curated by Sylvain Bellenger",
    credits: "Photo credits: Amedeo Benestante",
    summary:
      "Right from the title, the exhibition Blindness, Blinding, Outrage proposes a close relationship with " +
      "the enigmatic painting by Pieter Brueghel the Elder, the Parable of the Blind (1568). Three themes " +
      "arise: the simulation of scientific representation, the simulation of the disturbance of vision, and " +
      "hypervision, the effect of contemporary technological developments.\n\n" +
      "On display are 24 drawings (including a triptych composed of three sheets) in which the artist " +
      "reconciles objective and subjective drawing to highlight the relationship between artistic " +
      "representation and scientific knowledge. Some of the works are arranged on inclined bases, in " +
      "continuity with the exhibition logic of the Cabinet of Drawings, of which Capodimonte is one of the " +
      "richest and most prestigious examples in Italy. Finally, the large triptych that completes the " +
      "exhibition is dedicated to blindness, understood as a physical and symbolic fall, of which the artist " +
      "captures the different phases: abandonment, perception of the fall, attempt to get up again.\n\n— Sylvain Bellenger",
    works: [
      { src: img("p36_1.jpg"), title: "Cecità accecamento oltraggio", medium: "Installation view, Museo e Real Bosco di Capodimonte" },
      { src: img("p37_1.jpg"), title: "Parabola", medium: "Graphite and charcoal on paper — 70 × 100 cm (×3)" },
      { src: img("p38_1.jpg"), title: "Cheratectomia fotorefrattiva", medium: "Graphite and pastel on paper — 30.7 × 21.3 cm" },
      { src: img("p38_2.jpg"), title: "Leucoma corneale", medium: "Graphite, pastel, watercolour, gel medium on paper — 29.7 × 20.9 cm" },
      { src: img("p39_1.jpg"), title: "Untitled (bathygraphica)", medium: "Collage, textile, glue, acrylic, oil, pastels and graphite — 36.2 × 25.8 cm" },
      { src: img("p39_2.jpg"), title: "Untitled (bathygraphica)", medium: "Collage, textile, glue, acrylic, oil, pastels and graphite — 34 × 27.5 cm" },
    ],
  },
  {
    id: "ex-centrum",
    title: "Ex-centrum",
    year: "2021",
    venue: "There is No Time to Enjoy the Sun — Fondazione Morra Greco",
    curator: "Curated by Federico Delvecchio",
    credits: "Photo courtesy: Fondazione Morra Greco, Marco Casciello",
    summary:
      "This series is inspired by the idea of eccentricity, drawn up by the German philosopher Helmuth " +
      "Plessner. According to Plessner, the subject lives in a constant dialectic with the limit, recognizing " +
      "and overcoming it through technical features to ensure their survival. In other words, they " +
      "“artificially” draw limits and then “embody” them. Therefore human beings are " +
      "eccentrically positioned in the world: they are embedded in their limits and in their environment but, " +
      "at the same time, they’re also outside themselves, open to the world.\n\n" +
      "In the series, the eccentric relationship between contemporary space and the subjects which inhabit it " +
      "is observed from an embodied gaze that perceives its surroundings as hostile. Reflecting on the " +
      "disconnection between material existence and self-awareness, I explored the impact that is generated " +
      "where the materiality of the human body gets in touch with the spatial one and that generates dystopian " +
      "strategies of evasion, striving for the digital immateriality.",
    works: [
      { src: img("p40_1.jpg"), title: "Ex-centrum", medium: "Installation view, There’s no Time to Enjoy the Sun, Fondazione Morra Greco, Napoli" },
      { src: img("p42_1.jpg"), title: "Ex-centrum cabin", medium: "Graphite and pastels on paper — 15 × 21 cm" },
      { src: img("p42_2.jpg"), title: "Fenomenologia della sparizione", medium: "Graphite on paper — 20 × 20 cm (×3)" },
      { src: img("p42_3.jpg"), title: "Fenomenologia della sparizione", medium: "Graphite on paper — 20 × 20 cm (×3)" },
      { src: img("p42_4.jpg"), title: "Fenomenologia della sparizione", medium: "Graphite on paper — 20 × 20 cm (×3)" },
      { src: img("p42_5.jpg"), title: "Ex-centrum", medium: "Installation view, Fondazione Morra Greco, Napoli" },
      { src: img("p43_1.jpg"), title: "Vertigini", medium: "Charcoal and oil pastel on paper — 30 × 45 cm" },
      { src: img("p43_2.jpg"), title: "Mitopoiesi", medium: "Graphite and pastels on paper — 40 × 30 cm" },
    ],
  },
  {
    id: "your-body-is-a-battleground",
    title: "Your body is a battleground",
    year: "2020",
    venue: "Biennale Danza, Venezia",
    credits: "Photo credits: Biennale Danza, Venezia",
    summary:
      "Costume design and scenography — Silicon rubber, clay, plaster and oil paint.\n\n" +
      "Inspired by Barbara Krüger’s manifesto, the sculpture is a reflection on the ornamentation " +
      "symbolism imposed on the female body by the socio-political and media discourse. Created entirely in " +
      "silicon, the work consciously uses the material of cosmetic surgery to represent the gilded cage of the " +
      "canon of contemporary beauty. I worked on the material, kneading it as if it were bread, transforming " +
      "it into the flesh of an emptied body. I applied casts of different objects to it, as if the ornamental " +
      "symbols had left an indelible mark on that body. An unwanted mark, but considered beautiful by public opinion.",
    works: [
      { src: img("p45_1.jpg"), title: "Your body is a battleground", medium: "Silicon rubber, clay, plaster and oil paint" },
      { src: img("p45_2.jpg"), title: "Your body is a battleground", medium: "Silicon rubber, clay, plaster and oil paint" },
      { src: img("p46_1.jpg"), title: "Your body is a battleground", medium: "Costume design and scenography, Biennale Danza, Venezia" },
      { src: img("p46_2.jpg"), title: "Your body is a battleground", medium: "Costume design and scenography, Biennale Danza, Venezia" },
    ],
  },
  {
    id: "a-body-seen-from-a-screen",
    title: "A body seen from a screen",
    year: "2019",
    venue: "95 mixed media drawings",
    summary:
      "A screen is one of the most pervasive objects in everyday life. Our eyes stumble on these led-light " +
      "windows, developing such a close relationship to them that crashes of multiple visions accidentally " +
      "arise. In the perception of the ordinary, the sight from inside the screen and the one from outside " +
      "overlap each other.\n\n" +
      "Starting from this idea, I developed this series of drawings, in which the line acts as a moving eye, " +
      "in and out the bright blindness of virtuality. Exploring any fabric and dimension, this drawing eye " +
      "connects opposites and shows the simultaneous existence of each surface that, whether or not conscious, " +
      "surrounds us. In the intersection of divergent shades of colour and perspectives, the human body " +
      "contemplates its marginalized figure through the deforming mirror of the screen, becoming a diaphanous " +
      "matter that indistinctly merges with any other element. Forgetting oneself, it is caught in the moment " +
      "of its crumbling.",
    works: [
      { src: img("p48_1.jpg"), title: "Close-up II", medium: "Graphite and pastel on paper — 21 × 29 cm" },
      { src: img("p48_2.jpg"), title: "Close-up I", medium: "Graphite and pastel on paper — 21 × 29 cm" },
      { src: img("p49_1.jpg"), title: "Studio per una crocifissione", medium: "Graphite and pastel on paper — 42 × 22 cm" },
      { src: img("p49_2.jpg"), title: "Untitled", medium: "Oil pastel and pigments on paper — 15 × 20 cm" },
    ],
  },
  {
    id: "propriocezione",
    title: "Propriocezione",
    year: "2017",
    venue: "21 drawings, pencil and ballpoint pen on paper — 42 × 30 cm",
    summary:
      "This series of works arose from a research on anatomical drawings in ancient art history. Before " +
      "autopsy became a widely used technique, the representation of the interior of the human body depended " +
      "heavily on a mixture of religious, scientific, and philosophical thought at the same time. The results " +
      "are human bodies with three lungs, with hearts instead of stomachs and all sorts of inventions, just " +
      "like children use to draw interior body parts.\n\n" +
      "That’s the reason why I started this body of works as a way to become aware of proprioception. " +
      "I’ve enriched the vision of the body from the inside, using the blind drawing technique, and then " +
      "I melted it with information emerged from my memory and imagination. I tried to put myself in the same " +
      "perspective of an ancient human being or that of a child, giving rise to an anatomy of sensations.",
    works: [
      { src: img("p51_1.jpg"), title: "Propriocezione", medium: "Pencil and ballpoint pen on paper — 42 × 30 cm" },
      { src: img("p51_2.jpg"), title: "Propriocezione", medium: "Pencil and ballpoint pen on paper — 42 × 30 cm" },
      { src: img("p52_1.jpg"), title: "Propriocezione", medium: "Pencil and ballpoint pen on paper — 42 × 30 cm" },
      { src: img("p52_2.jpg"), title: "Propriocezione", medium: "Pencil and ballpoint pen on paper — 42 × 30 cm" },
    ],
  },
  {
    id: "man-with-a-permanent-mask",
    title: "Man with a permanent mask",
    year: "2016",
    venue: "22 drawings, ballpoint pen on paper — 50 × 70 cm",
    summary:
      "Unique subjects of this work are the photographic portraits collected on the internet of Richard " +
      "Norris, the first man to undergo a complete face transplant. In this series, I tried to go beyond the " +
      "traditional concept of portrait, turning my attention exclusively to the screen.\n\n" +
      "The drawings were made using the pure contour technique, an artistic process consisting of a constant " +
      "visual contact with the subject without ever looking at the drawing surface. There is no “model” " +
      "in the classical meaning here, since the figure drawing became digital. The portrait exercise, translated " +
      "into the interposition of the screen and the “blind drawing” process, becomes a continuous " +
      "questioning on my and his identity.",
    works: [
      { src: img("p54_1.jpg"), title: "Man with a permanent mask", medium: "Ballpoint pen on paper — 50 × 70 cm" },
      { src: img("p54_2.jpg"), title: "Man with a permanent mask", medium: "Ballpoint pen on paper — 50 × 70 cm" },
      { src: img("p55_1.jpg"), title: "Man with a permanent mask", medium: "Ballpoint pen on paper — 50 × 70 cm" },
      { src: img("p55_2.jpg"), title: "Man with a permanent mask", medium: "Ballpoint pen on paper — 50 × 70 cm" },
    ],
  },
];
