const PORTFOLIO_DATA = {
  "statement": "My artistic research investigates processes of memory and imagination \nas material forces that sediment, transform, and reorganize matter over \ntime. I explore forms of representation through different states of mat-\nter, treating materials as active agents that retain traces of environmen-\ntal, symbolic, and cultural stratifications. \nThese layered conditions reveal fragile ecological equilibriums and \nchallenge conventional understandings of landscape as a stable or pu-\nrely visual entity.\nRooted in painting and drawing, my practice expands into sculptural, \ninstallative, and video-based forms, where images become spatial and \nmatter behaves as a dynamic process. I am particularly interested in mo-\nments of collapse, transformation, and instability, where form remains \nprovisional and open to change. My works function as open systems, \nhosting fragments of symbolism and scientific observation, and acting \nas witnesses to irreversible events, sudden ruptures, and the merging of \nanatomical and geomorphic phenomena. \nThrough these processes, I seek to blur distinctions between body and \nlandscape, organic and inorganic, perception and materiality.\nStatement",
  "coverText": "Andrea Bolognino\nPortfolio",
  "projects": [
    {
      "id": "hyperobjects",
      "title": "Pictorial Hyperobjects",
      "years": "PHD Project",
      "pages": [
        3,
        4,
        5,
        6,
        7
      ],
      "cover": 4,
      "texts": {
        "3": "Pictorial Hyperobjects\nfor a contemporary expansion of landscape painting\nPHD Project in Visual Art and Creative Practices \nAcademy of Fine Arts Naples\nLooking at the contemporary landscape as the coexistence of hype-\nrobjects (Morton 2018), phenomena of such vast spatio-temporal di-\nmensions that they destabilize the dialectic between subject and object, \nthe IP project    seeks to produce a corpus of “pictorial hyperobjects” in \norder to interrogate and expand the pictorial medium through hybridiza-\ntion with sculpture and with digital images generated by GANs, CNNs, \nand RNNs.\nThe aim is to conduct a multidimensional inquiry into landscape throu-\ngh both material and digital experiments, with a particular focus on \nthe cartographic tool of the map. Starting from the conception of the \n“object” as active matter (Friedmann-Krauthausen 2021), IP addres-\nses crucial questions of the present: How does art respond to the life of \nobjects? Can painting subvert the perception of landscape as an object \nto be possessed, fostering instead an eco-critical awareness? Is it pos-\nsible to create a work that is viscous and unlimited (Morton 2018) like \nthe hyperobjects within which it is conceived?\nEarly experiments have focused on decomposition, using organic resi-\ndues and mold to generate surfaces marked by living traces. The erosion \nand disintegration of paper by microorganisms and insects produced \ncompositions reminiscent of aerial views of landscapes. While mold is \nusually associated with decay and death, the project reinterprets it as a \nsign of regeneration, situating these surfaces at the intersection of eco-\nlogical and political reflection.",
        "4": "Initial practice based research findings\nMicrorganisms, charcoal and oil on paper and plastic, dimensions variables",
        "5": "",
        "6": "",
        "7": "Extension of the practice into Video Art\ntriadic apparatus consisting of a macro lens attached to a smartphone camera, \nan endoscope, and a webcam + Vjing softwares.\nStills from video"
      }
    },
    {
      "id": "osservatorio",
      "title": "Osservatorio",
      "years": "2024",
      "pages": [
        8,
        9,
        10,
        11,
        12,
        13,
        14
      ],
      "cover": 9,
      "texts": {
        "8": "Osservatorio, 2024\nGalleria Acappella\nIt’s unsettling the constant branching out of the tentative gaze that  ob-\nserves a drawing or a canvas by Andrea Bolognino. \nA feeling of losing oneself in a labyrinth, only to find a pos-\nsible \nway \nout \nin \na \ndetail, \na \nmark, \na \nspecific \nshade. \nIn Bolognino’s work, observation manifests itself as a process of explo-\nration of the multiple layers and dimensions that make up the fabric of \nlife. His canvases and papers are veritable visual palimpsests, where \nimages overlap and undermine one another, creating a tangle of lines \nand forms that are as suggestive as they are enigmatic. \nThus, the artist moves away from the traditional idea of mimetic re-\npresentation to a more complex and diverse view of reality. Here is \nreified the kaleidoscope of references and quotations coming from \nthe cultural, historical, and personal influences, that chain up to \nform an actual archive of collective consciousness, where the past \nand the present merge into an evocative and profound synthesis. \nBolognino does not use painting as a space for representation. \nHe uses it as a plastic dimension in which the viewer and the matter \ndevelop a relationship capable of generating bewilderment.\nLucrezia Longobardi",
        "9": "Photo credits: Danilo Donzelli",
        "10": "Anelli di crescita\ncharcoal, graphiite, pastels and oil on paper on wood 95 x 150 cm\nSezione sottile di granito\ncharcoal, graphite, pastels and oil on paper on wood - 95 x 150 cm",
        "11": "La città é una macchina inutile\nplaster, acrylic, oil, collage, ink transfer, pastels on canvas - 184x149 cm",
        "12": "",
        "13": "Schwarzwald\ncharcoal, graphite, pastels and oil on paper - 18 x 25 cm\nCristalli di rame nativo\ncharcoal, oil and pastels on paper - 10 x 15 cm",
        "14": ""
      }
    },
    {
      "id": "il-guscio",
      "title": "Il Guscio",
      "years": "2022",
      "pages": [
        15,
        16,
        17
      ],
      "cover": 16,
      "texts": {
        "15": "Il Guscio, 2022\nOfficine San Carlo\ncurated by Lucrezia Longobardi and Nora De Blasio.\n‘Giving life to a space in disintegration, Bolognino’s work inhabits the \ndisillusionment of dreams abandoned while growing up, of all the ho-\npes and desires that animated the primary age and that, inevitably, have \nbeen let go to the oblivion of a present that does not allow distractions. \nThe quagmire is, therefore, the natural element in which to find all that \nwe have had to part with, along with the viscosity of time dissolved \nbehind us.’\nLucrezia Longobardi",
        "16": "Il Guscio - glass case, soil, plants, found objects, plaster,clay, glue, paper. - 250x300x300 cm",
        "17": ""
      }
    },
    {
      "id": "automa-autore",
      "title": "AUTOMA-AUTORE",
      "years": "2022",
      "pages": [
        18,
        19,
        20,
        21
      ],
      "cover": 20,
      "texts": {
        "18": "AUTOMA-AUTORE, 2022 \nGalleria UnosuNove\ncurated by Simone Zacchini\n \nThe work stems from the etymon of the word encyclopedia, from the \nGreek enkýklios paideîa, “circular instruction,” to investigate a space of \ncontact between art and science in which to allow a futuristic being-\nin-the-world to germinate. Thus, a condition is generated in which real \nand virtual overlap fluidly thanks to a yet unseen quality of technology, \nwhich amplifies the human, merging within it. \nIn conceiving the work, I was inspired by the impossible task of the pro-\ntagonist of La Macchina Mondiale (Paolo Volponi, 1965).",
        "19": "Installation view Figure Out, UnoSuNove Gallery, Rome\nPhoto credits: Giorgio Benni",
        "20": "Automa-Autore\ncharcoal and pigments on paper mounted on canvas - 150 x 230 cm.",
        "21": "Untitled from the series Automa-Autore\nwatercolour and graphite on paper - 30 x 22 cm\nUntitled from the series Automa-Autore\nwatercolour and charcoal on paper - 25 x 30 cm"
      }
    },
    {
      "id": "metamorphica",
      "title": "Metamorphica",
      "years": "2022/ongoing",
      "pages": [
        22,
        23,
        24,
        25
      ],
      "cover": 23,
      "texts": {
        "22": "Metamorphica, 2022/ongoing\nseries of mixed media drawings and paintings on different surfaces\nMetamorphica is an imaginative journey from the microscopic to the \nmacroscopic and vice versa. On my work table, I arranged object trou-\nvés accumulated over time. \nI spent my time observing and meditating on them and thus, with my \neyes closed, I landed on pluriform landscapes of memory and imagina-\ntion. Sometimes it is the texture or material of the objects that triggers \nan imaginative reaction, sometimes their composition, and sometimes \nthe variations of light that hit them. Each element is linked to the other \nin a constant stream of metamorphosis, from material to material, from \nleaf to fabric from fork to sea urchin.",
        "23": "Untitled (metamorphica)\ngraphite, pastels, oil and watercolour on paper\n45 x 30 cm\nUntitled (metamorphica)\ngraphite, pastels, oil and watercolour on paper\n55 x 37 cm",
        "24": "Untitled (metamorphica)\ncharcoal, glue, pigments, oil and acrylic on paperin wood frame\n35 x 30 cm",
        "25": "Il deserto dei Tartari\ncharcoal graphite pastels and oil on paper in wood frame\n15 x 20 (x3) cm"
      }
    },
    {
      "id": "i-giganti",
      "title": "I Giganti",
      "years": "2022",
      "pages": [
        26,
        27,
        28,
        29,
        30,
        31
      ],
      "cover": 31,
      "texts": {
        "26": "I Giganti, 2022 \nGalleria Acappella\nThe research project “I Giganti” came about as an attempt to transla-\nte the collection nachts leuchten die schiffe, by the German poet Nico \nBleutge, into my visual language.\nI retraced the poet’s path, finding myself in the first person on the trail \nof Alfred Döblin and, in particular, his science fiction novel Giganten \n(1932). The figure of Giants as beings formed from organic and inor-\nganic material in constant metamorphosis thus also stimulated my \nimagination, causing me to delve in another light into a pivotal point of \nmy poetics: the dialogue between the human body and the machine.",
        "27": "Photo credits: Danilo Donzelli",
        "28": "Kylin\ngraphite, oil and charcoal on paper\n100 x 70 cm\nWieschinska\ngraphite, oil and pastel on paper\n29 x 41 cm",
        "29": "Veli di tormalina - oil on paper - 21 x 29 cm",
        "30": "Scrolling\ngraphite, pastels, oil and collage on paper\n29 x 41 cm\nSenza Titolo (studio da Chaim Soutine)\ngraphite, oil and pastel on paper\n50 x 30 cm",
        "31": ""
      }
    },
    {
      "id": "corpo-aumentato",
      "title": "Corpo aumentato",
      "years": "2022",
      "pages": [
        32,
        33,
        34
      ],
      "cover": 33,
      "texts": {
        "32": "Corpo aumentato, 2022\nseries of mixed media paintings on polyester\nThe augmented body establishes a dialogue with the votive shrine as a \ncharacteristic architectural element of the city of Naples. \nWith this work, I started from the configuration of the body of the Saints, \nas a place where the presence of the divine is visible, often through mu-\ntilation and wounds, to reflect on the status of the contemporary body, \naugmented, hybridized, grafted by elements of an artificial and techno-\nlogical nature. \nThus, at the center of the installation is the idea of a new contamina-\nted anatomy, where imagination redesigns the human figure as a battle-\nground between biology and technological innovation.",
        "33": "Installation view and Untitled \nInstallation view and Untitled \n(corpo aumentato)\n(corpo aumentato)\noil, pigments and charcoal on polyester\noil, pigments and charcoal on polyester\n21 x 29 cm\n21 x 29 cm",
        "34": "Installation view and Untitled \n(corpo aumentato) \ncharcoal and acrylic on polyester\n21 x 29 cm"
      }
    },
    {
      "id": "cecita-accecamento-oltraggio",
      "title": "Cecità accecamento oltraggio",
      "years": "2022",
      "pages": [
        35,
        36,
        37,
        38,
        39,
        40
      ],
      "cover": 36,
      "texts": {
        "35": "Cecità accecamento oltraggio, 2022\nMuseo e Real Bosco di Capodimonte\ncurated by Sylvain Bellenger\nRight from the title, the exhibition Blindness, Blinding, Outrage propo-\nses a close relationship with the enigmatic painting by Pieter Brueghel \nthe Elder, the Parable of the Blind (1568). Three themes arouses: the \nsimulation of scientific representation, the simulation of the disturban-\nce of vision, and hypervision, the effect of contemporary technological \ndevelopments. \nOn display are 24 drawings (including a triptych composed of three she-\nets) in which the artist reconciles objective and subjective drawing to \nhighlight the relationship between artistic representation and scientific \nknowledge. \nSome of the works, are arranged on inclined bases, in continuity with \nthe exhibition logic of the Cabinet of Drawings, of which Capodimonte \nis one of the richest and most prestigious examples in Italy. \nFinally, the large triptych that completes the exhibition is dedicated to \nblindness, understood as a physical and symbolic fall, of which the ar-\ntist captures the different phases: abandonment, perception of the fall, \nattempt to get up again.\nSylvain Bellenger",
        "36": "Photo credits: Amedeo Benestante",
        "37": "Parabola\ngraphite and charcoal on paper\n70 x 100 cm (x3)",
        "38": "Cheratectomia fotorefrattiva\ngraphite and pastel on paper\n30,7 x 21,3 cm\nLeucoma corneale\ngraphite, pastel, watrcolour, gel medium on paper\n29,7 x 20,9 cm",
        "39": "Untitled (bathygraphica)\n2 of 4 drawings on paper\ncollage, textile, glue, acrylic, oil, pastels and graphite\n36,2 x 25,8 cm\n34 x 27,5 cm",
        "40": ""
      }
    },
    {
      "id": "ex-centrum",
      "title": "Ex-centrum",
      "years": "2021",
      "pages": [
        41,
        42,
        43
      ],
      "cover": 42,
      "texts": {
        "41": "Ex-centrum, 2021\nThere is No Time to Enjoy the Sun Fondazione Morra Greco\ncurated by Federico Delvecchio\nThis series is inspired by the idea of eccentricity, drawn up by the ger-\nman philosopher Helmuth Plessner.\nAccording to Plessner, the subject lives in a constant dialectic with the \nlimit, recognizing and overcoming it through technical features to ensu-\nre their survival. In other words, they “artificially” draw limits and then \n“embody” them. Therefore the human beings are eccentrically positio-\nned in the world: they are embedded in their limits and in their environ-\nment but, at the same time, they’re also outside themselves, open to \nthe world. \nIn the series, the eccentric relationship between contemporary space \nand the subjects, which inhabits it, is observed from an embodied gaze \nthat perceives its surroundings as hostile.\nReflecting on the disconnection between material existence and       sel-\nf-awareness, I explored the impact that is generated where the materia-\nlity of the human body gets in touch with the spatial one and that\ngenerates dystopian strategies of evasion, striving for the digital imma-\nteriality.",
        "42": "Installation view at\nFondazione Morra Greco, Napoli.\nThere’s no Time to Enjoy the Sun\nEx-centrum cabin\ngraphite and pastels on paper\n15 x 21 cm\nFenomenologia della  sparizione\ngraphite on paper\n20 x 20 cm (x3)\nPhoto courtesy: Fondazione\nMorra Greco, Marco Casciello",
        "43": "Vertigini\ncharcoal and oil pastel on paper\n30 x 45 cm\nMitopoiesi\ngraphite and pastels on paper\n40 x 30 cm"
      }
    },
    {
      "id": "your-body-is-a-battleground",
      "title": "Your body is a battleground",
      "years": "2020",
      "pages": [
        44,
        45,
        46
      ],
      "cover": 45,
      "texts": {
        "44": "Your body is a battleground, 2020\nBiennale Danza, Venezia\nCostume design and scenography - Silicon rubber, clay, plaster and oil paint\nInspired by Barbara Krüger’s manifesto, the sculpture is a reflection on \nthe ornamentations symbolism imposed on the female body by the so-\ncio-political and media discourse. \nCreated entirely in silicon, the work consciously uses the material of \ncosmetic surgery to represent the gilded cage of the canon of contem-\nporary beauty. \nI worked on the material, kneading it as if it were bread, transforming it \ninto the flesh of an emptied body. \nI applied casts of different objects to it, as if the ornamental symbols \nhad left an indelible mark on that body. \nAn unwanted mark, but considered beautiful by the public opinion.",
        "45": "",
        "46": "Photo credits: Biennale Danza, Venezia"
      }
    },
    {
      "id": "a-body-seen-from-a-screen",
      "title": "A body seen from a screen",
      "years": "2019",
      "pages": [
        47,
        48,
        49
      ],
      "cover": 48,
      "texts": {
        "47": "A body seen from a screen, 2019\n95 mixed media drawings\nA screen is one of the most pervasive objects in everyday life. \nOur eyes stumble on these led-lights windows, developing such a clo-\nse relationship to them that crashes of multiple visions accidentally \narise. In the perception of the ordinary, the sight from inside the screen \nand the one from outside overlap each other. \nStarting from this idea, I developed this series of drawings, in which the \nline acts as a moving eye, in and out the bright blindness of virtuality. \nExploring any fabric and dimension, this drawing eye connects op-\nposites and shows the simultaneous existence of each surface that, \nwhether or not conscious, surrounds us. \nIn the intersection of divergent shades of colour and perspectives, the \nhuman body contemplates its marginalized figure through the defor-\nming mirror of the screen, becoming a diaphanous matter that indi-\nstinctly merges with any other elements. \nForgetting oneself, it is caught in the moment of its crumbling.",
        "48": "Close-up II\ngraphite and pastel on paper\n21 x 29 cm\nClose-up I\ngraphite and pastel on paper\n21 x 29 cm",
        "49": "Studio per una crocifissione\ngraphite and pastel on paper\n42 x 22 cm\nUntitled\noil pastel pigments on paper\n15 x 20 cm"
      }
    },
    {
      "id": "propriocezione",
      "title": "Propriocezione",
      "years": "2017",
      "pages": [
        50,
        51,
        52
      ],
      "cover": 51,
      "texts": {
        "50": "Propriocezione, 2017\n21 drawings pencil and ballpoint pen on paper, 42 x 30 cm\nThis series of works arose from a research on anatomical drawings in \nancient art history. \nBefore autopsy became a widely used technique, the representation of \nthe interior of the human body depended heavily on a mixture of reli-\ngious, scientific, and philosophical thought at the same time. \nThe results are human bodies with three lungs, with hearts instead of \nstomachs and all sorts of inventions, just like children use to draw inte-\nrior body parts.\nThat’s the reason why I started this body of works as a  way to become \naware of proprioception. I’ve enriched the vision of the body from the \ninside, using the blind drawing technique, and then I melted it with infor-\nmations emerged from my memory and imagination. \nI tried to put myself in the same prospective of an ancient human being \nor that of a child, giving rise to an anatomy of sensations.",
        "51": "",
        "52": ""
      }
    },
    {
      "id": "man-with-a-permanent-mask",
      "title": "Man with a permanent mask",
      "years": "2016",
      "pages": [
        53,
        54,
        55
      ],
      "cover": 54,
      "texts": {
        "53": "Man with a permanent mask, 2016\n22 drawings ballpoint pen on paper, 50 x 70 cm\nUnique subjects of this work are the photographic portraits collected on \nthe internet of Richard Norris, the first man to undergo a complete face \ntransplant. \nIn this series, I tried to go beyond the traditional concept of portrait, tur-\nning my attention exclusively to the screen. \nThe drawings were made using the pure contour technique, an artistic \nprocess consisting of a constant visual contact with the subject without \never looking at the drawing surface. \nThere is no “model” in classical meaning here, since the figure drawing \nbecame digital. The portrait exercise, translated into the interposition \nof the screen and the “blind drawing” process, becomes a continuous \nquestioning on my and his identity.",
        "54": "",
        "55": ""
      }
    }
  ]
};
